# Generated by Django 5.2 on 2025-05-06 02:10

import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=landing.models.DynamicUploadPath())),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('folder', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
