# Generated by Django 5.2 on 2025-05-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_folder_remove_file_file_type_alter_file_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
