# Generated by Django 5.2 on 2025-05-06 05:18

import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_fileupload_uploaded_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='other', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=landing.models.DynamicUploadPath()),
        ),
    ]
