# Generated by Django 5.2 on 2025-05-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_delete_fileupload_file_file_type_alter_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('task_assign', models.CharField(choices=[('Monitoring', 'Monitoring'), ('Documentation', 'Documentation'), ('Analysis', 'Analysis'), ('Support', 'Support')], default='Monitoring', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
