# Generated by Django 5.2 on 2025-05-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_barangay_employee_alter_file_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='certificates_issued',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Incomplete', 'Incomplete')], default='Pending', max_length=50),
        ),
    ]
